unbind r
bind r source-file ~/.tmux.conf

set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# bind F2 copy-mode
bind F2 send-prefix \; copy-mode

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#latest' # See https://github.com/catppuccin/tmux/tags for additional tags
set -g @plugin 'jimeh/tmuxifier'


set-option -g status-position top

# My status bar config
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_tabs_enabled on
set -g @catppuccin_status_justify centre
set -g @catppuccin_status_modules_left "session"
set -g @catppuccin_status_modules_right "date_time"
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_middle_separator " | "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_current_fill "all"
set -g @catppuccin_status_left_separator "█"
set -g @catppuccin_status_right_separator "█"
set -g @catppuccin_date_time_text "󰭦 %Y-%m-%d 󰅐 %H:%M"



# Catpuccin prebuilt configs
# Config 1
# set -g @catppuccin_window_right_separator "█ "
# set -g @catppuccin_window_middle_separator " | "
# set -g @catppuccin_window_number_position "right"
#
# set -g @catppuccin_window_default_fill "none"
#
# set -g @catppuccin_window_current_fill "all"
#
# set -g @catppuccin_status_modules_right "application session user host date_time"
# set -g @catppuccin_status_left_separator "█"
# set -g @catppuccin_status_right_separator "█"
#
# set -g @catppuccin_date_time_text "%Y-%m-%d %H:%M:%S"
#
# # Config 2
# set -g @catppuccin_window_left_separator "█"
# set -g @catppuccin_window_right_separator "█ "
# set -g @catppuccin_window_number_position "right"
# set -g @catppuccin_window_middle_separator "  █"
#
# set -g @catppuccin_window_default_fill "number"
#
# set -g @catppuccin_window_current_fill "number"
# set -g @catppuccin_window_current_text "#{pane_current_path}"
#
# set -g @catppuccin_status_modules_right "application session date_time"
# set -g @catppuccin_status_left_separator  ""
# set -g @catppuccin_status_right_separator " "
# set -g @catppuccin_status_fill "all"
# set -g @catppuccin_status_connect_separator "yes"


# Config 3
# set -g @catppuccin_window_left_separator ""
# set -g @catppuccin_window_right_separator " "
# set -g @catppuccin_window_middle_separator " █"
# set -g @catppuccin_window_number_position "right"
#
# set -g @catppuccin_window_default_fill "number"
# set -g @catppuccin_window_default_text "#W"
#
# set -g @catppuccin_window_current_fill "number"
# set -g @catppuccin_window_current_text "#W"
#
# set -g @catppuccin_status_modules_right "directory user host session"
# set -g @catppuccin_status_left_separator  " "
# set -g @catppuccin_status_right_separator ""
# set -g @catppuccin_status_fill "icon"
# set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_directory_text "#{pane_current_path}"

# Additional config options
# set -g @catppuccin_pane_border_style "fg=#{thm_blue}" # Use a value compatible with the standard tmux 'pane-border-style'
# set -g @catppuccin_pane_active_border_style "fg=#{thm_orange}" # Use a value compatible with the standard tmux 'pane-border-active-style'
# set -g @catppuccin_menu_style "default" # Use a value compatible with the standard tmux `menu-style`
set-option -g pane-base-index 1 # Set pane-base-index to 1 to match tmux catppuccin_window_default_text
set-option -g base-index 1 # Set base-index to 1 to match tmux catppuccin_window_default_text



# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
